# -*- coding: utf-8 -*-
"""Copy of FINBERT_Actual_Video!!!!!!!!!!!.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f17S6fNpuKRbMNR6HTbpb1e4tbVlLCWJ

# Sentiment Analysis of Financial Text Data from News Article Summaries from Alpha Vantage using the Huggingface transformer library.


### Typical LLM Process

* Usually you have some sort of "base" pre-trained model and then you fine-tune it to your specific dataset.

##### Pre-training: (MASSIVE TRAINING SET!)
* Involves training a model on a large, generic dataset to learn broad language understanding, without focusing on specific tasks.
* For ChatGPT you train on good chunk of the internet, you get an Internet document completer with undefined behavior.

#### Fine-tuning: (SMALL, SPECIFIC TRAINING SET!)
* Adapts the pre-trained model to a specific task by training on a smaller, task-specific dataset, optimizing the model for particultar objectives.
* With ChatGPT fine tune on assistant training data where question is on top and answer is below. A question-answerer in other words.
* For example, in our case financial news sentiment classfication of "Bearish","Bullish", or "Neutral" would be the task.

#### Reinforcement Learning From Human FeedBack
* Let model respond and different raters rate which response is better so can predict which candidate response is more desirable and run PPO to fine tune this sampling policy so answers that ChatGPT gives better answer with respect to reward.

### Hugging Face
"
👋 Hi!

We are on a mission to democratize good machine learning, one commit at a time.
"

https://huggingface.co/

### Hugging Face Transformer Library
* Comprehensive open-source AI library across various domains like Natural Language Processing (NLP) + Computer Vision + Audio.
  - It has many pre-trained an fine tuned models in its model hub. https://huggingface.co/models
  - It has tools for fine-tuning and building upon pre-trained models
* User-friendly: Eases the creation and deployment of NLP models with PyTorch and TensorFlow integration for customization.
* Versatile: Includes multilingual support and offers comprehensive tools to build upon existing models.

### BERT (Bidirectional Encoder Representations from Transformers) by Google as base model
* A revolutionary pre-trained language model that captures contextual relationships in text, enabling state-of-the-art performance across various natural language processing tasks
* Bert Pretraining:
  - Masked Language Model (MLM) randomly hides some words in a sentence and trains the model to predict them based on their context
  - Next Sentence Prediction (NSP) involves understanding the relationship between two sentences.

### Finbert
* "Pre-trained BERT knew how to talk, but now it was time to teach it how to talk like a trader. We took the pre-trained BERT and then further trained it on a purely financial corpus called Reuters TRC2."
* Fine-tuning with labeled data for financial sentiment classification with the Financial Phrasebank. "It is a very well thought-out and carefully labeled albeit a small dataset. Researchers extracted 4500 sentences from various news articles, which include financial terms. Then 16 experts and master students with finance backgrounds labeled them. They didn’t only report labels but also inter-annotator agreement level for each sentence, which means how many experts labelled as positive, neutral and negative."
*The later Yi Yang et al released finbert-tone model "is the FinBERT model fine-tuned on 10,000 manually annotated (positive, negative, neutral) sentences from analyst reports. This model achieves superior performance on financial tone analysis task."
* https://github.com/yya518/
* https://huggingface.co/yiyanghkust/finbert-tone

### Goal of this video

#### 1. Do sentiment analysis on alpha-vantage dataset using pre-trained FinBert model using Transformers' *Pipeline* module which basically abstracts everything into:
  * Input: Sentence.
  * Output: Sentiment Score.

#### 2. Fine-tune this model to alpha-vantage dataset using Transformers' *Trainer* module.

## Preliminaries
### Need a GPU
### Installs necessary libraries then restart
"""

!pip install --upgrade accelerate datasets

"""#### Imports"""

# Pytorch Deep Learning
import torch
# Pandas+Numpy
import numpy as np
import pandas as pd
# Sklearn metrics
from sklearn.metrics import balanced_accuracy_score,accuracy_score

# Hugging Face Transformer Libraries
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline,Trainer, TrainingArguments
# Hugging Face Datasets
from datasets import Dataset

"""##### Check if GPU is available and set it to device variable"""

if torch.cuda.is_available():
    print("CUDA available. GPU will be used for computation.")
    device = 0  # Default to the first GPU; adjust if you have multiple GPUs
else:
    print("CUDA not available. Using CPU for computation.")
    device = -1  # Indicates CPU usage

"""### Load Alpha Vantage Sentiment Dataset
*
"""

df = pd.read_csv("alpha_vantage_sentiment_TSLA.csv")
df.head()

"""* Rename from summary to text since Bert trainer assumes this by default..."""

df.rename({"summary":"text"},axis=1,inplace=True)

"""### Look at label distribution"""

df[['Original_Sentiment_Label_Text','Sentiment_Label_Text']].value_counts(normalize=True)

df['time_published'].min(),df['time_published'].max()

"""## Inference in NLP: Language models predict or analyze text (e.g., answering questions, generate text (i.e ChatGPT), or classify sentiment in our case.
* Tokenizer for NLP: Breaks text into tokens (like words or characters or bytes) for the model.
* Numerical Conversion: Tokens are mapped to numbers, making them understandable to models.

## Approach 1: Manual Approach: Predict sentiment directly using the model and tokenizer without Pipeline
* Load model and tokenizer from model
  * First time you run it it takes a lot longer since it needs to download model
  * to_device is to put it on GPU
"""

# Model name from Model Hub
model_name = 'yiyanghkust/finbert-tone'
# Load model
model = AutoModelForSequenceClassification.from_pretrained(model_name).to(device)
# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

"""##### Note we can look at model config
* label2id gives us label to Id
* id2label gives up id to label

### Attention is all you need. Transformer (AI) revolution!
https://arxiv.org/pdf/1706.03762.pdf
"""

model.config

id_2_label = model.config.id2label
id_2_label

"""* Convert sentence into tokens"""

sentence = "The market outlook is very positive thanks to the new economic policies."

inputs = tokenizer(sentence, return_tensors="pt", padding=True, truncation=True, max_length=512)

inputs

# To make all tensors on same device
inputs = {k: v.to(device) for k, v in inputs.items()}

"""* Use Pytorch or Tensorflow (in this case Pytorch) to make a prediction on the input tokens.

"""

with torch.no_grad():
    outputs = model(**inputs)
outputs

"""* From the outputs we get a the logit predictions for each class 0,1,2
* Take argmax to find most likely class
"""

predictions = np.argmax(outputs.logits.cpu().numpy(), axis=1)

predictions

"""### Map this class to its meaning
* 0: Positive
* 1: Negative
* 2: Neutral
"""

# Map the array elements using a list comprehension
mapped_array = [id_2_label[element] for element in predictions]

print(mapped_array)

"""## Approach 2: Transformer Pipeline Approach
* Basically everything in the manual approach for you in 1 step.

* Transformer Pipeline for NLP: Streamlines tasks by:
  - Auto-tokenizing text.
  - Performing model inference (like text analysis or generation).
  - Providing straightforward results, abstracting away technical complexities.

* Don't forget to specify device since we don't want to run on CPU!


#### Load the sentiment analysis pipeline with the FinBERT model
* Note here I specify the model name from model-hub
"""

# Model name from Model Hub
model_name = 'yiyanghkust/finbert-tone'

sentiment_pipeline = pipeline(task="sentiment-analysis", model=model_name,batch_size=128,device=device)

sentiment_pipeline(sentence)

"""* Can also specify the model and tokenizer to create the pipeline"""

sentiment_pipeline = pipeline(task="sentiment-analysis",model=model,tokenizer=tokenizer,batch_size=128,device=device)

sentiment_pipeline(sentence)

sentence = "The market outlook is very negative thanks to the new economic policies."
sentiment_pipeline(sentence)

sentence = "The market outlook is very neutral thanks to the new economic policies."
sentiment_pipeline(sentence)

sentence = "The market outlook is unknown neutral."
sentiment_pipeline(sentence)

"""#### Now Let's Make Predictions on Entire DataSet to See How model Performs out of the Box
* Note with CPU only this takes a lot, lot longer!
"""

preds = sentiment_pipeline(df['text'].tolist())

preds[0:20]

"""* Extract just the prediction name from label key"""

df['prediction']=[pred['label'] for pred in preds]

"""* We can see how model is doing

"""

df.groupby(['Original_Sentiment_Label_Text','prediction']).size()

df.groupby(['Sentiment_Label_Text','prediction']).size()

balanced_accuracy_score(df['Sentiment_Label_Text'],df['prediction'])

accuracy_score(df['Sentiment_Label_Text'],df['prediction'])

"""##### For fine-tuning we will need indices 0,1,2 for labels instead of names so let's use model.config.label2id to create this colum"""

model.config.label2id

df['label']=df['Sentiment_Label_Text'].apply(lambda l:model.config.label2id[l])
df['label'].value_counts()

"""### Split into train/val/test for later comparison.
* For simplicity we split based on time.
  - First 60% train
  - Next 20% val
  - Next 20% test
* This can be problematic a bit since class balance changes over time and some articles on boundries between train/val or val/test have some overlap, but completely beats bias of stratified sample usually used since some articles are literally on same thing, but maybe different sources.

"""

train_end_point = int(df.shape[0]*0.6)
val_end_point = int(df.shape[0]*0.8)
df_train = df.iloc[:train_end_point,:]
df_val = df.iloc[train_end_point:val_end_point,:]
df_test = df.iloc[val_end_point:,:]
print(df_train.shape, df_test.shape, df_val.shape)

"""#### Test set accuracy before fine-tuning"""

preds=sentiment_pipeline(df_test['text'].tolist())
df_test['prediction']=[pred['label'] for pred in preds]
balanced_accuracy_score(df_test['Sentiment_Label_Text'],df_test['prediction'])

accuracy_score(df_test['Sentiment_Label_Text'],df_test['prediction'])

"""### Fine-tuning using trainer class from Hugging Face!
* Convert to huggingface datasets for preparation for fine-tuning
"""

# Converting pandas DataFrames into Hugging Face Dataset objects:
dataset_train = Dataset.from_pandas(df_train)
dataset_val = Dataset.from_pandas(df_val)
dataset_test = Dataset.from_pandas(df_test)

# Tokenizing the datasets:
dataset_train = dataset_train.map(lambda e: tokenizer(e['text'], truncation=True, padding='max_length', max_length=128), batched=True)
dataset_val = dataset_val.map(lambda e: tokenizer(e['text'], truncation=True, padding='max_length', max_length=128), batched=True)
dataset_test = dataset_test.map(lambda e: tokenizer(e['text'], truncation=True, padding='max_length' , max_length=128), batched=True)

# Setting the dataset format: (needed for Pytorch?)
dataset_train.set_format(type='torch', columns=['input_ids', 'token_type_ids', 'attention_mask', 'label'])
dataset_val.set_format(type='torch', columns=['input_ids', 'token_type_ids', 'attention_mask', 'label'])
dataset_test.set_format(type='torch', columns=['input_ids', 'token_type_ids', 'attention_mask', 'label'])


# Shuffle the training dataset
dataset_train_shuffled = dataset_train.shuffle(seed=42)  # Using a seed for reproducibility

"""### Define trainer to fine tune model"""

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    return {'balanced_accuracy' : balanced_accuracy_score(predictions, labels),'accuracy':accuracy_score(predictions,labels)}

args = TrainingArguments(
    output_dir='temp/',
    evaluation_strategy='epoch',
    save_strategy='epoch',
    logging_strategy="steps",  # Log every X steps
    logging_steps=50,  # Log every 50 steps
    learning_rate=2e-6,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.1,
    load_best_model_at_end=True,
    metric_for_best_model='balanced_accuracy',
)

trainer = Trainer(
        model=model,                         # the instantiated 🤗 Transformers model to be trained
        args=args,                  # training arguments, defined above
        train_dataset=dataset_train_shuffled,         # training dataset
        eval_dataset=dataset_val,            # evaluation dataset
        compute_metrics=compute_metrics
)

"""#### Train the model!"""

trainer.train()

"""#### Can use trainer.predict method to make predictions on test set."""

predictions = trainer.predict(dataset_test)
predictions

"""##### Can also use trained model as part of a pipeline by
* Saving locally
* Uploading to Model Hub

Here we save locally
"""

model_path = "path/to/save/model"


# Save the model
trainer.model.save_pretrained(model_path)

# Save the tokenizer associated with the model
# Save the tokenizer
tokenizer.save_pretrained(model_path)

"""###### Load the trained model into a pipeline.  """

trained_pipeline = pipeline("text-classification", model=model_path, tokenizer=model_path,device=device)

"""##### Make Predictions and evaluate accuracy"""

preds=trained_pipeline(df_test['text'].tolist())
df_test['prediction']=[pred['label'] for pred in preds]

"""##### Calculate the balanced accuracy score"""

# Calculate the balanced accuracy score
score = balanced_accuracy_score(df_test['Sentiment_Label_Text'], df_test['prediction'])
print(f"Balanced Accuracy Score: {score}")

# Calculate the balanced accuracy score
score = accuracy_score(df_test['Sentiment_Label_Text'], df_test['prediction'])
print(f"Accuracy Score: {score}")

